### PR TITLE
Android uses request code 24 from now on

### PR DESCRIPTION
**Pull request by ened**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

To prevent issues with the location_permissions plugin, as it's being used from geolocator.

### :arrow_heading_down: What is the current behavior?

Conflicts with location_permissions.. details in #111 

### :new: What is the new behavior (if this is a feature change)?

Change request code.

### :bug: Recommendations for testing

include geolcoator in example - test permissions like call or storage,

### :memo: Links to relevant issues/docs

Consider to set proper request codes for all BaseflowIT plugins to avoid any further conflicts.

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/BaseflowIT/flutter-geolocator/blob/develop/CONTRIBUTING.md))
- [x] Relevant documentation was updated
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by ened** [comment]
@mvanbeusekom consider cutting a public release soon and also amend the README about the plugin conflict

**Comment by mvanbeusekom** [comment]
@ened really grateful for your pull-request, however could you elaborate on your remark:

> Consider to set proper request codes for all BaseflowIT plugins to avoid any further conflicts.

What do you mean with "proper"? Is there any additional documentation I can read through to make sure this doesn't happen again and also not conflicts with other plugins (not by Baseflow)?

**Comment by ened** [comment]
You can not avoid conflicts with other plugins. Root cause is this line here:

https://github.com/BaseflowIT/flutter-permission-handler/blob/develop/android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java#L122

Both the `location_permissions` plugin and `permission_handler` register the same request code. However, `location_permissions` get's called earlier and thus eats the permission request result (by returning true, so Flutter won't deliver the event to the next plugin that is interested in the permission result), in this case `permission_handler`.

By proper I meant you should introduce a 3rd party dependency to hold all of the BaseflowIT constants (all the request codes).

I also would not worry about other plugins. How many permission handling plugins can a developer install & use? ;-).
The numbers themselves should be a bit higher I think.

**Comment by ened** [comment]
BTW, the bit about 3rd party library to keep all the constants assumes that you probably want to start  a collection of plugins to handle each permission individually. 

permission_handler currently contains code for every permission and most notably, requires iOS developers to put permission strings in their configuration even when they don't need certain permissions. So splitting it up would be very welcome.

**Comment by mvanbeusekom** [comment]
Got it, thank you for the explanation. 

The idea is indeed to phase out / replace the `permission_handler` by individual packages that will be available in the `baseflowit/flutter-permission-plugins` repository. I will definitely consider including a separate library containing request codes for each individual package their.

**Comment by ened** [comment]
@mvanbeusekom just noticed I have opened PRs against the master branch.. guess you could merge develop into master once and I will open future PRs against develop, if needed. (hopefully not, though!)

**Comment by ened** [comment]
@mvanbeusekom and #108 made it to develop. Sorry for that mess.

**Comment by mvanbeusekom** [comment]
No worries I will fix it on my end ;)

**Pull request merged**
